[local]
localhost

[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost

[user]
user-dev.manidevops.online

[cart]
cart-dev.manidevops.online

[mysql]
mysql-dev.manidevops.online

[shipping]
shipping-dev.manidevops.online

[rabbitmq]
rabbitmq-dev.manidevops.online

[payment]
payment-dev.manidevops.online

[frontend]
frontend-dev.manidevops.online

